SELECT DISTINCT
SOH.SOHNUM_0,
SOH.YSTUNAM_0,
PRH.PRHNUM_0,
PRH.YMOPICKER_0,
SOH.YORDSRC_0,
PRH.CREDAT_0,
SOH.CREDAT_0,
DATEDIFF(day,PRH.CREDAT_0, SOH.CREDAT_0)

FROM SORDER SOH
LEFT OUTER JOIN STOPRED PRD
ON UPPER(SOH.YSTUNAM_0) = PRD.ORINUM_0
LEFT OUTER JOIN STOPREH PRH
ON PRD.PRHNUM_0 = PRH.PRHNUM_0

WHERE
SOH.CREDAT_0 >= %1%
       AND (SOH.CREDAT_0 <= %2%
              OR RTRIM(%2%) IS NULL
              OR RTRIM(%2%) = '' )

AND

SOH.YORDSRC_0 BETWEEN 4 AND 6

ORDER BY SOH.CREDAT_0 DESC